### ISSUE TITLE
refinements to syntax (feedback requested)

### ISSUE THREAD

**Issue by neuromusic** [napari/napari-plugin-devtools#9]
Love the first implementation of this tool!!

I think we have an opportunity to improve the syntax of the tool with two key changes:

1. give plugin developers more fine-grained control over the functionality
2. anticipating that this tool may expand its functionality in the future beyond just plugin validation by "bucketing" functionality

As a first pass at a proposal...

# plugin validation
all functionality related to validating a plugin would be contained under `npd validate`
- `npd validate --help` would display help on validating plugins
- `npd validate` alone would EITHER display "help" OR run all validation checks with sensible defaults

## plugin validation: packages
- `npd validate -p/--package=<target>` would perform package-level validation of a specific target file (a filepath or URL to a source distribution or wheel). 
- `npd validate -p/--package` If no target is defined, it would default to validating all package assets found in `dist/` (that is, the current functionality of `npd --validate-package`)

## plugin validation: hooks
- `npd validate -h/--hook=<specification>` would perform validation of a particular hook specification
- `npd validate -h/--hook` If no target is defined, it would perform validation on all hook implementations that the CLI tool is aware of (current functionality of `npd --validate-functions` would become `npd validate --hook=napari_experimental_provide_function`)

# display help
`npd` or `npd --help`
- shows help for the `npd` command line tool (see #6)

Thoughts? @tlambert03? @sofroniewn? @ziyangczi ?

**Comment by sofroniewn** [comment]
Overall I really like your syntax proposals @neuromusic.

I was expecting to be able to do something like `npd validate-packages package_name`. I think your proposal of `npd validate --package`. I could alternatively consider `npd validate --include` and `npd validate --exclude`, where `npd validate` would use all packages, `--include` would use just those listed in include (could be a list). `--exclude` would use all apart from those listed in `exclude`.

I worry `-h` for `--hook` is confusing with `-h` for `--help`, but I like `--hook`, so not quite sure what to do there. I think that allowing people to pass the name of the hook spec is much nicer than `validate-functions` etc, as it will grow with our hookspecs.

I'd also allow the `--include` and `--hook` functionality to be combined, so that you could look at just the one hook spec with a certain package (right now if i try and run a specific hookspec for a package i'm interested in, i just get loads of info from one of my other packages which has a bunch of stuff in it).

I think the test now that is done with `valdiate-packages` I might rename with `--discover` (or you could just keep this as `--package`, if we're now using `--include`), so you could do things like

```
npd validate --include napari-demo --discover # to just get discover for this package
npd validate --include napari-demo --hook= napari_experimental_provide_function # to just get this hook for this package
npd validate --include napari-demo # to get discover and all hooks for this package
npd validate --discover # to get discover and all packages
```

How does this sound? cc @LCObus with whom I just did some user testing!

**Comment by neuromusic** [comment]
>I worry -h for --hook is confusing with -h for --help, but I like --hook, so not quite sure what to do there. 

yeah, same. perhaps `npd validate -k/--hook`?

**Comment by sofroniewn** [comment]
> yeah, same. perhaps npd validate -k/--hook?

works for me!
